
CHOOSE_LANGUAGE = "choose_language"
CHOOSE_UNIVERSITY = "choose_university"
GIVE_USERNAME = "give_username"
GIVE_PASSWORD = "give_password"
NAME = "name"
NEPTUN_CODE = "neptun_code"
CODE = "code"
COURSE_INFORMATIONS = "course_informations"
CREDIT = "credit"
CREDITS = "credits"
RECOMMENDED_SEMESTER = "recommended_semester"
ENROLLMENT_TIMES = "enrollment_times"
TYPE = "type"
RESULT = "result"
REQUIRED_CREDITS = "required_credits"
ACQUIRED_CREDITS = "acquired_credits"
CREDITS_UNDER_PROGRESS_IN_CURRENT_SEMESTER = "credits_under_progress_in_current_semester"
OPTIONAL_COURSES_ARE_NOT_CALCULATED = "optional_courses_are_not_calculated"
PERSONAL_INFORMATIONS = "personal_informations"
TEXT_COMMANDS = "text_commands"
COMMANDS = "commands"
PRESS_KEY = "press_key"
ESC = "esc" 
AFTER_ESC_TEXT = "after_esc_text"

